<a href="https://colab.research.google.com/github/LucasFaleirosMoreira/university-studies/blob/main/PL_01_04_2025.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

#matrizes
A = np.matrix([[1, 1, 1, 0, 0], #essa função "formata" a matriz
               [3, 1, 0, 1, 0],
               [-1, 3, 0, 0, 1]])

b = np.matrix([[5],
               [12],
               [7]])

c = np.matrix({[-2],
               [-4],
               [0],
               [0],
               [0]})


base = [2, 3, 4]

#matriz B
B =

#solução
x = np.linalg.inv(A) * b #essa função inverte a matriz
print(x)


#se eu coloco : em alguma das "posições" na matriz ele traz todos numeros dessa posiçao (no exemplo abaixo ele traz
#todos numeros da terceira coluna)
print(A[:,2])

c = [0,2]
print(A[:,c])

[[ 7.]
 [ 9.]
 [-8.]]
[[3]
 [4]
 [5]]
[[1 3]
 [2 4]
 [4 5]]
