<a href="https://colab.research.google.com/github/LucasFaleirosMoreira/university-studies/blob/main/PL_15_04_2025_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Importando biblioteca Numpy
import numpy as np

In [ ]:
# Dados de entrada ligas metálicas
A = np.matrix([[1, 1, 1, 0, 0],
               [3, 1, 0, 1, 0],
               [-1, 3, 0, 0, 1]])

b = np.matrix([[5],
               [12],
               [7]])

c = np.matrix([[-2],
               [-4],
               [0],
               [0],
               [0]])

base = [2, 3, 4]

In [ ]:
# Matriz B
B = np.matrix(A[:,base])
print("B =")
print(B)

print()

# Solução básica
xB = np.linalg.inv(B) * b
print("xB =")
print(xB)

B =
[[1 0 0]
 [0 1 0]
 [0 0 1]]

xB =
[[ 5.]
 [12.]
 [ 7.]]


In [ ]:
# Vetor pT
pT = c[base].T * np.linalg.inv(B)
print("pT = ", pT)

# Custos relativos
s = c.T - pT * A
print("s = ", s)

pT =  [[ 0.          0.         -1.33333333]]
s =  [[-3.33333333  0.          0.          0.          1.33333333]]


In [ ]:
# Verifica se a solução é ótima
mins = s.min() # Calcula o valor mínimo de s
p1 = s.argmin() # Retorna a posição do valor mínimo no vetor s
print("mins = ", mins)
print("p1 = ", p1)

mins =  -3.333333333333333
p1 =  0


In [ ]:
# Vetor auxiliar y
y = np.linalg.inv(B) * A[:,p1]
print("y =")
print(y)
print()

# Teste da razão
r = xB / y
print("r =")
print(r)
print()

# Eliminando valores negativos do vetor r
r[r < 0] = np.inf
print("r =")
print(r)

y =
[[ 1.33333333]
 [ 3.33333333]
 [-0.33333333]]

r =
[[ 2. ]
 [ 2.9]
 [-7. ]]

r =
[[2. ]
 [2.9]
 [inf]]


In [ ]:
# Determina variável que sai da base
minr = r.min()
p2 = r.argmin()
print("minr = ", minr)
print("p2 = ", p2)

minr =  2.0000000000000004
p2 =  0


In [ ]:
# Atualiza a base
base[p2] = int(p1)
print(base)

[0, 3, 1]


In [ ]:
# Solução ótima
x = np.zeros([c.size,1]) # Cria matriz nula para escrever a solução
x[base] = xB # Coloca os valores da solução básica nas posições corretas da matriz de solução

for i in range(c.size):
  print("x[{}] = {}".format(i+1,x[i,0]))

x[1] = 2.0
x[2] = 3.0
x[3] = 0.0
x[4] = 3.0
x[5] = 0.0


In [ ]:
# Valor ótimo
vo = (c.T * x) * (-1)
print("Valor ótimo = ",vo[0,0])

Valor ótimo =  16.0
